// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_path_ from "./routes/[...path].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_cineboxd from "./routes/api/cineboxd.ts";
import * as $api_cron_refresh_cache from "./routes/api/cron/refresh-cache.ts";
import * as $api_shortlink from "./routes/api/shortlink.ts";
import * as $index from "./routes/index.tsx";
import * as $s_code_ from "./routes/s/[code].tsx";
import * as $HomePage from "./islands/HomePage.tsx";
import * as $MovieCard from "./islands/MovieCard.tsx";
import * as $MovieList from "./islands/MovieList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $_path_,
    "./routes/_app.tsx": $_app,
    "./routes/api/cineboxd.ts": $api_cineboxd,
    "./routes/api/cron/refresh-cache.ts": $api_cron_refresh_cache,
    "./routes/api/shortlink.ts": $api_shortlink,
    "./routes/index.tsx": $index,
    "./routes/s/[code].tsx": $s_code_,
  },
  islands: {
    "./islands/HomePage.tsx": $HomePage,
    "./islands/MovieCard.tsx": $MovieCard,
    "./islands/MovieList.tsx": $MovieList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
